//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.261
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESVSnip.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TESVSnip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _14_layer_deletelayer {
            get {
                object obj = ResourceManager.GetObject("_14_layer_deletelayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_back {
            get {
                object obj = ResourceManager.GetObject("agt_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_forward {
            get {
                object obj = ResourceManager.GetObject("agt_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_stop {
            get {
                object obj = ResourceManager.GetObject("agt_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 确定? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureInquiry {
            get {
                return ResourceManager.GetString("AreYouSureInquiry", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_add {
            get {
                object obj = ResourceManager.GetObject("bookmark_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 不能剪切整个MOD 的本地化字符串。
        /// </summary>
        internal static string Cannot_cut_a_plugin {
            get {
                return ResourceManager.GetString("Cannot_cut_a_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能复制父节点不同的多个节点 的本地化字符串。
        /// </summary>
        internal static string CannotCopyNodesFromDifferentParents {
            get {
                return ResourceManager.GetString("CannotCopyNodesFromDifferentParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能复制整个MOD 的本地化字符串。
        /// </summary>
        internal static string CannotCopyPlugin {
            get {
                return ResourceManager.GetString("CannotCopyPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能拖放父节点不同的多个节点 的本地化字符串。
        /// </summary>
        internal static string CannotDragNodesWithDifferentParents {
            get {
                return ResourceManager.GetString("CannotDragNodesWithDifferentParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能拖放至子项目内(否则将导致循环错误!) 的本地化字符串。
        /// </summary>
        internal static string CannotDropOnDescendent {
            get {
                return ResourceManager.GetString("CannotDropOnDescendent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法解析 RecordStructure.xml 文件. 部分记录编辑功能将失效. 的本地化字符串。
        /// </summary>
        internal static string CannotParseRecordStructure {
            get {
                return ResourceManager.GetString("CannotParseRecordStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MOD的 cell, world 或 dial 结构错误, 自动修复失败 的本地化字符串。
        /// </summary>
        internal static string CannotSanitizeLooseGroups {
            get {
                return ResourceManager.GetString("CannotSanitizeLooseGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MOD包含了无法识别的记录,自动修复失败 的本地化字符串。
        /// </summary>
        internal static string CannotSanitizeUnknownRecords {
            get {
                return ResourceManager.GetString("CannotSanitizeUnknownRecords", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap checkedbox {
            get {
                object obj = ResourceManager.GetObject("checkedbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkedbox1 {
            get {
                object obj = ResourceManager.GetObject("checkedbox1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClearFiltering {
            get {
                object obj = ResourceManager.GetObject("ClearFiltering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 关闭已打开的MOD,将会丢失未保存的内容,是否继续? 的本地化字符串。
        /// </summary>
        internal static string CloseActivePluginInquiry {
            get {
                return ResourceManager.GetString("CloseActivePluginInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭所有已打开的MOD,将会丢失未保存的内容,是否继续? 的本地化字符串。
        /// </summary>
        internal static string CloseAllLoseChangesInquiry {
            get {
                return ResourceManager.GetString("CloseAllLoseChangesInquiry", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ColumnFilterIndicator {
            get {
                object obj = ResourceManager.GetObject("ColumnFilterIndicator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configure_toolbars {
            get {
                object obj = ResourceManager.GetObject("configure_toolbars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string Copy_Record_to_Clipboard {
            get {
                return ResourceManager.GetString("Copy_Record_to_Clipboard", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deletecell {
            get {
                object obj = ResourceManager.GetObject("deletecell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 删除提示 的本地化字符串。
        /// </summary>
        internal static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_add {
            get {
                object obj = ResourceManager.GetObject("edit_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_remove {
            get {
                object obj = ResourceManager.GetObject("edit_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_UndoHS {
            get {
                object obj = ResourceManager.GetObject("Edit_UndoHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editclear {
            get {
                object obj = ResourceManager.GetObject("editclear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditTable {
            get {
                object obj = ResourceManager.GetObject("EditTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emptybox {
            get {
                object obj = ResourceManager.GetObject("emptybox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大型文件需要占用大量内存载入.是否设置排除该文件? 的本地化字符串。
        /// </summary>
        internal static string ESM_Large_File_Size_Inquiry {
            get {
                return ResourceManager.GetString("ESM_Large_File_Size_Inquiry", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap fileexport {
            get {
                object obj = ResourceManager.GetObject("fileexport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 过滤器设置 的本地化字符串。
        /// </summary>
        internal static string Filter_Options_Text {
            get {
                return ResourceManager.GetString("Filter_Options_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Filtering {
            get {
                object obj = ResourceManager.GetObject("Filtering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Find2 {
            get {
                object obj = ResourceManager.GetObject("Find2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 初始化设置 的本地化字符串。
        /// </summary>
        internal static string FirstLoadOptions {
            get {
                return ResourceManager.GetString("FirstLoadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完整编辑器 的本地化字符串。
        /// </summary>
        internal static string FullRecordEditorTitle {
            get {
                return ResourceManager.GetString("FullRecordEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请再次确认你正在进行什么操作,是否继续? 的本地化字符串。
        /// </summary>
        internal static string GeneralSpellWarningInquiry {
            get {
                return ResourceManager.GetString("GeneralSpellWarningInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap insertcell {
            get {
                object obj = ResourceManager.GetObject("insertcell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap insertcell1 {
            get {
                object obj = ResourceManager.GetObject("insertcell1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\flomajor\f31500\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Ti [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string LoadWarning {
            get {
                return ResourceManager.GetString("LoadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首次载入 &apos;skyrim.esm&apos; 文件.需要占用大量内存.是否设置分类过滤器控制载入? 的本地化字符串。
        /// </summary>
        internal static string MainView_FirstTimeSkyrimLoad_ExcludeInquiry {
            get {
                return ResourceManager.GetString("MainView_FirstTimeSkyrimLoad_ExcludeInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mod丢失 的本地化字符串。
        /// </summary>
        internal static string Missing_Plugin {
            get {
                return ResourceManager.GetString("Missing_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录丢失 的本地化字符串。
        /// </summary>
        internal static string Missing_Record {
            get {
                return ResourceManager.GetString("Missing_Record", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap move_task_down {
            get {
                object obj = ResourceManager.GetObject("move_task_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap move_task_up {
            get {
                object obj = ResourceManager.GetObject("move_task_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 未载入mod 的本地化字符串。
        /// </summary>
        internal static string No_Plugins_Loaded {
            get {
                return ResourceManager.GetString("No_Plugins_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选中MOD. 的本地化字符串。
        /// </summary>
        internal static string NoPluginSelected {
            get {
                return ResourceManager.GetString("NoPluginSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选中MOD,操作终止. 的本地化字符串。
        /// </summary>
        internal static string NoPluginSelectedCannotContinue {
            get {
                return ResourceManager.GetString("NoPluginSelectedCannotContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选中MOD,保存终止 的本地化字符串。
        /// </summary>
        internal static string NoPluginSelectedToSave {
            get {
                return ResourceManager.GetString("NoPluginSelectedToSave", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 TES4记录丢失,操作终止 的本地化字符串。
        /// </summary>
        internal static string PluginLacksAValidTes4RecordCannotContinue {
            get {
                return ResourceManager.GetString("PluginLacksAValidTes4RecordCannotContinue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap quick_restart {
            get {
                object obj = ResourceManager.GetObject("quick_restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload_all_tabs {
            get {
                object obj = ResourceManager.GetObject("reload_all_tabs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 是否立即重启程序应用编码设置(注意修改是否已经保存) 的本地化字符串。
        /// </summary>
        internal static string RestartText {
            get {
                return ResourceManager.GetString("RestartText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Revert {
            get {
                object obj = ResourceManager.GetObject("Revert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RolledBack {
            get {
                object obj = ResourceManager.GetObject("RolledBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 这个文件可能被修改或删除内容,是否保存? 的本地化字符串。
        /// </summary>
        internal static string SavePluginWithFilterAppliedInquiry {
            get {
                return ResourceManager.GetString("SavePluginWithFilterAppliedInquiry", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 共找到{0}个 的本地化字符串。
        /// </summary>
        internal static string SearchProgressChanged_Items_Found {
            get {
                return ResourceManager.GetString("SearchProgressChanged_Items_Found", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SortAscending {
            get {
                object obj = ResourceManager.GetObject("SortAscending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SortDescending {
            get {
                object obj = ResourceManager.GetObject("SortDescending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap special_paste {
            get {
                object obj = ResourceManager.GetObject("special_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon tesv_ico {
            get {
                object obj = ResourceManager.GetObject("tesv_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 剪贴板是空的 的本地化字符串。
        /// </summary>
        internal static string TheClipboardIsEmpty {
            get {
                return ResourceManager.GetString("TheClipboardIsEmpty", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap xdays {
            get {
                object obj = ResourceManager.GetObject("xdays", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
